#!/usr/bin/env zsh

# Like time, but only displays elapsed time in seconds.
#
# Add the following line for auto-completion:
# _comps[duration]=_precommand

autoload -U jln-unalias-exec

_duration_run() {
  local TIMEFMT='%*E'
  time $@
}

duration() {
  jln-unalias-exec 0 1 _duration_run $@
}

duration $@
