#!/usr/bin/env zsh

# Apply a function on each of the arguments
#
# $ each cmd arg1 arg2
# equivalent to
# $ cmd arg1
# $ cmd arg2
#
# -- is used to mark end of options
#
# $ each cmd opt -- arg1 arg2
# equivalent to
# $ cmd opt arg1
# $ cmd opt arg2
#
# For further usage, please consider zargs command
#
# Add the following line for auto-completion:
# _comps[each]=_precommand

local -i iargs=${@[(ie)--]}
local cmd=${(q)1}
if (( $iargs > $# )); then
  iargs=1
elif (( $iargs > 2 )); then
  cmd+=' '${(q)${@[2,$iargs-1]}}
fi

for f in $@[$iargs+1,-1]; do
  eval "$cmd ${(q)f}"
done
