#!/usr/bin/env zsh

setopt localoptions errreturn

for f in "$@" ; do
  if [[ -f $f ]] ; then
    case "$f" in
      *.rar|*.cbr)       unrar x "$f"    ;;
      *.zip|*.cbz|*.jar) unzip "$f"      ;;
      *.tar.gz|*.tgz)    tar xzf "$f"    ;;
      *.gz)              gunzip "$f"     ;;
      *.tar.zst)         tar --zstd -xf "$f" ;;
      *.zst)             unzstd "$f"     ;;
      *.tar)             tar xf "$f"     ;;
      *.tar.bz2|*.tbz2)  tar xjf "$f"    ;;
      *.tar.xz|*.tar.lz) tar xJf "$f"    ;;
      *.bz2)             bunzip2 "$f"    ;;
      *.Z)               uncompress "$f" ;;
      *.7z)              7z x "$f"       ;;
      *.deb)             /usr/bin/ar vx "$f" ;;
      *) echo -E "$0: '$f' has an unsupported extension" >&2 ; return 2;;
    esac
  else
    echo -E "$0: '$f' is not a regular file" >&2 ; return 1
  fi
done
