#!/usr/bin/env zsh

# Unroll aliases used with sudo
#
# alias l='ls -CF'
# smart-sudo l
# Equivalent to
# smart-sudo ls -CF
#

if [[ -n $1 ]]; then
  if [[ $1 == '-'* ]]; then
    command sudo $@
  else
    autoload -U jln-unalias-exec
    jln-unalias-exec 0 1 'command sudo' $@
  fi
else
  #if no parameters were given, then assume we want a root shell
  command sudo -s
fi
