#!/usr/bin/env zsh

# Insert a space at the beginning of the command, then execute it.
# With `setopt hist_ignore_space`, entering a space at the beginning
# prevents it from being saved in the history.
#
# When the cli is empty up-history is used beforehand.

emulate -L zsh

[[ -z $BUFFER ]] && zle up-history
if [[ $BUFFER != [[:space:]]* ]]; then
   LBUFFER=" $LBUFFER"
fi
zle accept-line
