#!/usr/bin/env zsh

# Moves to the start of the previous argument
# supports NUMERIC

emulate -L zsh -o extendedglob

local lwords pat

lwords=(${(Z:n:)LBUFFER})

if (( NUMERIC > 1 )); then
  if (( NUMERIC > $#lwords )); then
    CURSOR=0
  else
    local -i end=$#lwords i
    for ((i=end-NUMERIC+1; i <= end; ++i)); do
      pat+=${(q)lwords[i]}'[[:space:]]#'
    done
    eval CURSOR='${#LBUFFER%%'$pat'}'
  fi
else
  CURSOR=${#LBUFFER%%${lwords[-1]}[[:space:]]#}
fi
