#!/usr/bin/env zsh

# Moves to the start of the previous argument
# supports NUMERIC

emulate -L zsh -o extendedglob

local words pat

words=(${(Z:n:)LBUFFER})

if (( NUMERIC > 1 )); then
  if (( NUMERIC > $#words )); then
    CURSOR=0
  else
    local -i end=$#words i
    for (( i=end-NUMERIC+1; i <= end; ++i )); do
      pat+='${words['$i']}[[:space:]]#'
    done
    eval CURSOR='${#LBUFFER%%'$pat'}'
  fi
else
  CURSOR=${#LBUFFER%%${words[-1]}[[:space:]]#}
fi
