#!/usr/bin/env zsh

# Insert or remove sudo at the start of the line

emulate -L zsh -o extendedglob

local match mbegin mend

if [[ $BUFFER = (#b)([[:space:]]#)(#e) ]]; then
  zle up-history
  if [[ -n $match[1] ]]; then
    LBUFFER=$match[1]$LBUFFER
  fi
fi

if [[ $BUFFER = (#b)([[:space:]]#)(sudo[[:space:]]|)* ]]; then
  if [[ -z $match[2] ]]; then
    BUFFER="${match[1]}sudo ${BUFFER[$mend[2]+1,-1]}"
    if (( $CURSOR > $#match[1] )); then
      CURSOR+=5
    fi
  else
    if (( $CURSOR > $#match[1] )); then
      CURSOR+=-$#match[2]
    fi
    BUFFER="${match[1]}${BUFFER[$mend[2]+1,-1]}"
  fi
fi
