#!/usr/bin/env zsh

# Start an interactive sub-shell and inserts the result
# of a command under the cursor position

autoload -U read-from-minibuffer

jln-insert-command() {
  emulate -L zsh

  local REPLY
  read-from-minibuffer 'command: '
  [[ -z $REPLY ]] && return
  LBUFFER+=$REPLY
}

jln-insert-command
